//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSharpCode.XamlDesigner.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect MainWindowRect {
            get {
                return ((global::System.Windows.Rect)(this["MainWindowRect"]));
            }
            set {
                this["MainWindowRect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<LayoutRoot>\r\n  <RootPanel Orientation=\"" +
            "Horizontal\">\r\n    <LayoutPanel Orientation=\"Horizontal\">\r\n      <LayoutPanel Ori" +
            "entation=\"Horizontal\" DockHeight=\"1.05701504319986*\">\r\n        <LayoutAnchorable" +
            "PaneGroup Orientation=\"Vertical\" DockWidth=\"280\">\r\n          <LayoutAnchorablePa" +
            "ne DockWidth=\"280\" DockHeight=\"6*\">\r\n            <LayoutAnchorable AutoHideMinWi" +
            "dth=\"100\" AutoHideMinHeight=\"100\" Title=\"Toolbox\" IsSelected=\"True\" ContentId=\"T" +
            "oolbox\" CanClose=\"False\" />\r\n          </LayoutAnchorablePane>\r\n          <Layou" +
            "tAnchorablePane DockHeight=\"3*\">\r\n            <LayoutAnchorable AutoHideMinWidth" +
            "=\"100\" AutoHideMinHeight=\"100\" Title=\"Outline\" IsSelected=\"True\" ContentId=\"Outl" +
            "ine\" CanClose=\"False\" />\r\n          </LayoutAnchorablePane>\r\n        </LayoutAnc" +
            "horablePaneGroup>\r\n        <LayoutDocumentPaneGroup Orientation=\"Horizontal\">\r\n " +
            "         <LayoutDocumentPane>\r\n            <LayoutDocument Title=\"New1\" IsSelect" +
            "ed=\"True\" IsLastFocusedDocument=\"True\" LastActivationTimeStamp=\"07/08/2018 11:20" +
            ":21\" />\r\n          </LayoutDocumentPane>\r\n        </LayoutDocumentPaneGroup>\r\n  " +
            "      <LayoutAnchorablePaneGroup Orientation=\"Vertical\" DockWidth=\"280\">\r\n      " +
            "    <LayoutAnchorablePane DockWidth=\"280\" DockHeight=\"0.434261617468999*\" Floati" +
            "ngWidth=\"290\" FloatingHeight=\"285\" FloatingLeft=\"1625\" FloatingTop=\"163\">\r\n     " +
            "       <LayoutAnchorable AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"T" +
            "humbnail\" IsSelected=\"True\" ContentId=\"Thumbnail\" FloatingLeft=\"1625\" FloatingTo" +
            "p=\"163\" FloatingWidth=\"290\" FloatingHeight=\"285\" CanClose=\"False\" LastActivation" +
            "TimeStamp=\"07/08/2018 11:18:44\" />\r\n          </LayoutAnchorablePane>\r\n         " +
            " <LayoutAnchorablePane DockHeight=\"1.565738382531*\">\r\n            <LayoutAnchora" +
            "ble AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Properties\" IsSelected" +
            "=\"True\" ContentId=\"Properties\" CanClose=\"False\" />\r\n          </LayoutAnchorable" +
            "Pane>\r\n        </LayoutAnchorablePaneGroup>\r\n      </LayoutPanel>\r\n    </LayoutP" +
            "anel>\r\n    <LayoutAnchorablePaneGroup Orientation=\"Horizontal\" DockWidth=\"25\" Do" +
            "ckHeight=\"149\" FloatingWidth=\"290\" FloatingHeight=\"229\" FloatingLeft=\"816\" Float" +
            "ingTop=\"1137\">\r\n      <LayoutAnchorablePane Id=\"b34155a2-262a-49a6-a4ca-cb01e268" +
            "4268\" DockHeight=\"149\" FloatingWidth=\"290\" FloatingHeight=\"229\" FloatingLeft=\"81" +
            "6\" FloatingTop=\"1137\" />\r\n    </LayoutAnchorablePaneGroup>\r\n  </RootPanel>\r\n  <T" +
            "opSide />\r\n  <RightSide>\r\n    <LayoutAnchorGroup>\r\n      <LayoutAnchorable AutoH" +
            "ideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Behaviors\" ContentId=\"Behaviors" +
            "\" CanClose=\"False\" />\r\n    </LayoutAnchorGroup>\r\n    <LayoutAnchorGroup>\r\n      " +
            "<LayoutAnchorable AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Triggers" +
            "\" ContentId=\"Triggers\" CanClose=\"False\" />\r\n    </LayoutAnchorGroup>\r\n  </RightS" +
            "ide>\r\n  <LeftSide />\r\n  <BottomSide>\r\n    <LayoutAnchorGroup PreviousContainerId" +
            "=\"b34155a2-262a-49a6-a4ca-cb01e2684268\">\r\n      <LayoutAnchorable AutoHideMinWid" +
            "th=\"100\" AutoHideMinHeight=\"100\" Title=\"Errors\" ContentId=\"Errors\" FloatingLeft=" +
            "\"816\" FloatingTop=\"1137\" FloatingWidth=\"290\" FloatingHeight=\"229\" CanClose=\"Fals" +
            "e\" LastActivationTimeStamp=\"07/08/2018 11:20:02\" />\r\n    </LayoutAnchorGroup>\r\n " +
            " </BottomSide>\r\n  <FloatingWindows />\r\n  <Hidden />\r\n</LayoutRoot>")]
        public string AvalonDockLayout {
            get {
                return ((string)(this["AvalonDockLayout"]));
            }
            set {
                this["AvalonDockLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>%ProgramFiles%\Reference Assemblies\Microsoft\Framework\v3.0\PresentationFramework.dll</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AssemblyList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AssemblyList"]));
            }
            set {
                this["AssemblyList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.WindowState MainWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
    }
}
